name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B clean package -DskipTests

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Tests
      run: |
        mvn -B test \
          -Dcucumber.filter.tags="@smoke" \
          -Dcucumber.plugin="pretty, json:target/cucumber-reports/cucumber.json, junit:target/surefire-reports/TEST-cucumber.xml" \
          -Dallure.results.directory=target/allure-results

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          target/surefire-reports/**/*
          target/allure-results/**/*
          target/cucumber-reports/**/*

  report:
    name: Generate Report
    needs: test
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Test Results
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: test-results/


    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v2
      if: always()
      with:
        allure_results: test-results
        gh_pages: false
        enable_chart: true
        report_name: 'Test Report'
        report_path: ./allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-report
        retention-days: 5

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-raw
        path: test-results/
        retention-days: 5
